const { DataTypes } = require('sequelize');

/**
 * KitchenKOT schema factory for hotel-specific data
 * Manages Kitchen Order Tickets (KOT) for restaurant orders
 */
const createKitchenKOTModel = (sequelize, schemaName) => {
  return sequelize.define(
    'KitchenKOT',
    {
      id: {
        type: DataTypes.UUID,
        defaultValue: DataTypes.UUIDV4,
        primaryKey: true,
      },
      kotNumber: {
        type: DataTypes.STRING,
        allowNull: false,
        unique: true,
      },
      billId: {
        type: DataTypes.UUID,
        allowNull: false,
      },
      tableNo: {
        type: DataTypes.STRING,
        allowNull: false,
      },
      guestName: {
        type: DataTypes.STRING,
        allowNull: true,
      },
      items: {
        // JSON array: [{ id, name, quantity, section, notes, status, preparationTime }]
        type: DataTypes.JSONB,
        allowNull: false,
        defaultValue: [],
      },
      section: {
        // e.g. "Grill", "Tandoor", "Bakery", "Main", "All"
        type: DataTypes.STRING,
        allowNull: true,
      },
      status: {
        type: DataTypes.ENUM('Pending', 'Preparing', 'Ready', 'Cancelled', 'Completed'),
        allowNull: false,
        defaultValue: 'Pending',
      },
      assignedChefId: {
        type: DataTypes.STRING,
        allowNull: true,
      },
      assignedChefName: {
        type: DataTypes.STRING,
        allowNull: true,
      },
      preparationStartTime: {
        type: DataTypes.DATE,
        allowNull: true,
      },
      preparationEndTime: {
        type: DataTypes.DATE,
        allowNull: true,
      },
      estimatedTime: {
        // minutes
        type: DataTypes.INTEGER,
        allowNull: true,
      },
      printedAt: {
        type: DataTypes.DATE,
        allowNull: true,
      },
      printCount: {
        type: DataTypes.INTEGER,
        allowNull: false,
        defaultValue: 0,
      },
      notes: {
        type: DataTypes.TEXT,
        allowNull: true,
      },
      autoGenerated: {
        type: DataTypes.BOOLEAN,
        allowNull: false,
        defaultValue: false,
      },
    },
    {
      tableName: 'kitchen_kots',
      schema: schemaName,
      timestamps: true,
      indexes: [
        { fields: ['kotNumber'] },
        { fields: ['billId'] },
        { fields: ['tableNo'] },
        { fields: ['status'] },
        { fields: ['section'] },
        { fields: ['assignedChefId'] },
        { fields: ['createdAt'] },
      ],
    },
  );
};

module.exports = createKitchenKOTModel;
