const { DataTypes } = require('sequelize');
const { sequelize } = require('../config/database');

/**
 * Global notifications table (not per-hotel schema).
 * Stores user-visible alerts that may be generated by the system.
 */
const Notification = sequelize.define(
  'Notification',
  {
    id: {
      type: DataTypes.UUID,
      defaultValue: DataTypes.UUIDV4,
      primaryKey: true,
    },
    hotelId: {
      type: DataTypes.STRING,
      allowNull: true,
    },
    type: {
      type: DataTypes.STRING(64), // e.g. LOW_AVAILABILITY, PAYMENT_PENDING
      allowNull: false,
    },
    level: {
      type: DataTypes.ENUM('info', 'warning', 'critical'),
      allowNull: false,
      defaultValue: 'info',
    },
    title: {
      type: DataTypes.STRING(255),
      allowNull: false,
    },
    message: {
      type: DataTypes.TEXT,
      allowNull: true,
    },
    isRead: {
      type: DataTypes.BOOLEAN,
      allowNull: false,
      defaultValue: false,
    },
    meta: {
      type: DataTypes.JSONB,
      allowNull: true,
      defaultValue: {},
    },
  },
  {
    tableName: 'notifications',
    timestamps: true,
    indexes: [
      { fields: ['hotelId'] },
      { fields: ['type'] },
      { fields: ['isRead'] },
    ],
  }
);

module.exports = Notification;

